export type JourneyStep = {
  key: string; stage: string; title: string; summary: string; duration: string;
  documents: string[]; pitfalls: string[]; actions: string[]; href?: string;
};

export const JOURNEY: JourneyStep[] = [
  { key:"budget",stage:"Prepare",title:"Work out your budget and deposit",summary:"Set a realistic ceiling including fees, duty, and a cash buffer.",duration:"1–2 weeks",documents:["Payslips and salary certificates","Bank and savings statements","Proof of deposit and gift letter, if relevant"],pitfalls:["Using every euro for the deposit","Forgetting legal, survey and insurance costs"],actions:["Run the affordability calculator","Check your credit report","Avoid taking new credit"],href:"/calculator" },
  { key:"aip",stage:"Prepare",title:"Apply for Approval in Principle",summary:"Ask a lender or regulated broker to assess your initial borrowing range.",duration:"1–4 weeks",documents:["Photo ID and proof of address","6 months of current-account statements","Employment and income records"],pitfalls:["Treating AIP as a loan guarantee","Letting documents become out of date"],actions:["Compare more than the headline rate","Confirm AIP expiry and refresh requirements"] },
  { key:"search",stage:"Find",title:"View, bid, and go Sale Agreed",summary:"Research recent sales, set a firm bid ceiling, and pay a refundable booking deposit.",duration:"Variable",documents:["AIP evidence","Proof of funds","Booking deposit receipt"],pitfalls:["Assuming Sale Agreed is legally binding","Skipping planning or neighbourhood checks"],actions:["Check the Property Price Register","Ask what is included in the sale","Appoint a solicitor early"] },
  { key:"checks",stage:"Check",title:"Solicitor, survey, and snagging",summary:"Your solicitor investigates title; your surveyor checks the physical property.",duration:"2–6 weeks",documents:["Sales advice note","Contract pack and title documents","Survey or snag report"],pitfalls:["Confusing a bank valuation with a survey","Using an unqualified inspector"],actions:["Arrange an independent survey","Send issues to your solicitor before signing"],href:"/guides/survey-and-snagging" },
  { key:"offer",stage:"Check",title:"Review the formal loan offer",summary:"Check the rate, term, special conditions, expiry, and what must happen before drawdown.",duration:"1–3 weeks",documents:["Formal loan offer","European Standardised Information Sheet","Valuation report"],pitfalls:["Missing special conditions","Changing jobs or borrowing before drawdown"],actions:["Ask your solicitor to explain the offer","Track every pre-drawdown condition"],href:"/documents" },
  { key:"contract",stage:"Commit",title:"Sign contracts and fund the balance",summary:"Only sign after legal and property checks are satisfactory and finance is secure.",duration:"1–2 weeks",documents:["Contract for Sale","Replies to requisitions","Deposit funds"],pitfalls:["Signing before loan conditions are satisfied","Assuming the booking deposit is the full contract deposit"],actions:["Confirm the completion date","Send the balance only to verified bank details"],href:"/documents" },
  { key:"insurance",stage:"Commit",title:"Put required insurance in place",summary:"Arrange mortgage protection and buildings insurance in time for drawdown.",duration:"2–6 weeks",documents:["Mortgage protection policy","Buildings or block policy schedule","Lender interest noted on policy"],pitfalls:["Leaving medical underwriting too late","Buying duplicate buildings cover for an apartment"],actions:["Start protection applications early","Confirm cover start date with lender"],href:"/guides/insurance" },
  { key:"closing",stage:"Close",title:"Close, draw down, and pay stamp duty",summary:"Your solicitor completes the purchase, files the return, and progresses registration.",duration:"1–5 days to close; registration may take longer",documents:["Closing statement","Stamp duty return","Deed of transfer"],pitfalls:["Last-minute source-of-funds queries","Confusing registration time with access to the home"],actions:["Complete a final inspection","Keep closing statements and receipts"],href:"/guides/stamp-duty" },
  { key:"move",stage:"Move",title:"Collect keys and set up the home",summary:"Record meters, transfer utilities, update LPT details, and handle the practical handover.",duration:"First 1–2 weeks",documents:["Meter readings and account numbers","BER certificate","Warranty and appliance documents"],pitfalls:["Not photographing meter readings","Missing management-company contacts"],actions:["Redirect post and update address","Check TV Licence requirement","Create a maintenance folder"] },
];
